name: Update Blocklist

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Aggregator
      run: python aggregator.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'AdShield Bot'
        git config --global user.email 'bot@adshield.app'
        git add blocklist.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update blocklist $(date +'%Y-%m-%d')" && git push)
